name: DevSecOps Pipeline
on: [push, pull_request]

jobs:
  security_scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Secret Scanning (Gitleaks)
      - name: Gitleaks Secret 
        #continue-on-error: true
        #uses: gitleaks/gitleaks-action@v2

        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  GITLEAKS_CONFIG: .gitleaks.toml
        #with:
        #  args: --path=src --connfig=gitleaks.toml -v 
        run: |
          mkdir -p results
          docker run --rm \
            -v "$PWD:/repo" \
            zricethezav/gitleaks:v8.24.3 \
            detect \
            --source /repo/src \
            --no-git \
            --config /repo/.gitleaks.toml \
            --redact \
            -v \
            --report-format json \
            --report-path /repo/results/gitleaks-report.json




      # 2. SAST (Semgrep) - Scanning for SQLi, Cmd Injection, XSS
      
      - name: Install Semgrep
        run: python3 -m pip install semgrep

      - name: Semgrep SAST
        run: semgrep scan --config auto --error .
        #continue-on-error: true

      # 3. SCA (Snyk) - Scanning requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r src/requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Open Source Scan
        #continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --file=src/requirements.txt  --severity-threshold=high
 
      # 4. Container Scan (Trivy)
      - name: Build Docker Image
        run: docker build -f src/Dockerfile -t vuln-store:latest src
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        #continue-on-error: true
        with:
          image-ref: 'vuln-store:latest'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
